// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyFlow.DAL.Data;

#nullable disable

namespace StudyFlow.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240911005704_AddCourseWithHisRelations")]
    partial class AddCourseWithHisRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProfileUser", b =>
                {
                    b.Property<int>("ListProfileId")
                        .HasColumnType("int");

                    b.Property<Guid>("ListUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListProfileId", "ListUserId");

                    b.HasIndex("ListUserId");

                    b.ToTable("ProfileUser");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsoCode = "AFG",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            IsoCode = "ALB",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            IsoCode = "DZA",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            IsoCode = "AND",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            IsoCode = "AGO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            IsoCode = "ATG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            IsoCode = "ARG",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            IsoCode = "ARM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            IsoCode = "AUS",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            IsoCode = "AUT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            IsoCode = "AZE",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            IsoCode = "BHS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            IsoCode = "BHR",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            IsoCode = "BGD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            IsoCode = "BRB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            IsoCode = "BLR",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            IsoCode = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            IsoCode = "BLZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            IsoCode = "BEN",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            IsoCode = "BTN",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            IsoCode = "BOL",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            IsoCode = "BIH",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            IsoCode = "BWA",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            IsoCode = "BRA",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            IsoCode = "BRN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            IsoCode = "BGR",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            IsoCode = "BFA",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            IsoCode = "BDI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            IsoCode = "CPV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            IsoCode = "KHM",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            IsoCode = "CMR",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            IsoCode = "CAN",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            IsoCode = "CAF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            IsoCode = "TCD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            IsoCode = "CHL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            IsoCode = "CHN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            IsoCode = "COL",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            IsoCode = "COM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            IsoCode = "COG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 40,
                            IsoCode = "COD",
                            Name = "Congo, Democratic Republic of the"
                        },
                        new
                        {
                            Id = 41,
                            IsoCode = "CRI",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            IsoCode = "HRV",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            IsoCode = "CUB",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            IsoCode = "CYP",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            IsoCode = "CZE",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 46,
                            IsoCode = "DNK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 47,
                            IsoCode = "DJI",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48,
                            IsoCode = "DMA",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            IsoCode = "DOM",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50,
                            IsoCode = "ECU",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 51,
                            IsoCode = "EGY",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 52,
                            IsoCode = "SLV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 53,
                            IsoCode = "GNQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 54,
                            IsoCode = "ERI",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 55,
                            IsoCode = "EST",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 56,
                            IsoCode = "SWZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 57,
                            IsoCode = "ETH",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 58,
                            IsoCode = "FJI",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 59,
                            IsoCode = "FIN",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 60,
                            IsoCode = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = 61,
                            IsoCode = "GAB",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 62,
                            IsoCode = "GMB",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 63,
                            IsoCode = "GEO",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 64,
                            IsoCode = "DEU",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 65,
                            IsoCode = "GHA",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 66,
                            IsoCode = "GRC",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 67,
                            IsoCode = "GRD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 68,
                            IsoCode = "GTM",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 69,
                            IsoCode = "GIN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 70,
                            IsoCode = "GNB",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 71,
                            IsoCode = "GUY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 72,
                            IsoCode = "HTI",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 73,
                            IsoCode = "HND",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 74,
                            IsoCode = "HUN",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 75,
                            IsoCode = "ISL",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 76,
                            IsoCode = "IND",
                            Name = "India"
                        },
                        new
                        {
                            Id = 77,
                            IsoCode = "IDN",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 78,
                            IsoCode = "IRN",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 79,
                            IsoCode = "IRQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 80,
                            IsoCode = "IRL",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 81,
                            IsoCode = "ISR",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 82,
                            IsoCode = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 83,
                            IsoCode = "JAM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 84,
                            IsoCode = "JPN",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 85,
                            IsoCode = "JOR",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 86,
                            IsoCode = "KAZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 87,
                            IsoCode = "KEN",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 88,
                            IsoCode = "KIR",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 89,
                            IsoCode = "PRK",
                            Name = "Korea, North"
                        },
                        new
                        {
                            Id = 90,
                            IsoCode = "KOR",
                            Name = "Korea, South"
                        },
                        new
                        {
                            Id = 91,
                            IsoCode = "KWT",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            IsoCode = "KGZ",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            IsoCode = "LAO",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            IsoCode = "LVA",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            IsoCode = "LBN",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            IsoCode = "LSO",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            IsoCode = "LBR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            IsoCode = "LBY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            IsoCode = "LIE",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            IsoCode = "LTU",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            IsoCode = "LUX",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            IsoCode = "MDG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            IsoCode = "MWI",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            IsoCode = "MYS",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            IsoCode = "MDV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            IsoCode = "MLI",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            IsoCode = "MLT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            IsoCode = "MHL",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            IsoCode = "MRT",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            IsoCode = "MUS",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            IsoCode = "MEX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            IsoCode = "FSM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            IsoCode = "MDA",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            IsoCode = "MCO",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            IsoCode = "MNG",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            IsoCode = "MNE",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            IsoCode = "MAR",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            IsoCode = "MOZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            IsoCode = "MMR",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 120,
                            IsoCode = "NAM",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            IsoCode = "NRU",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            IsoCode = "NPL",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            IsoCode = "NLD",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            IsoCode = "NZL",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            IsoCode = "NIC",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            IsoCode = "NER",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            IsoCode = "NGA",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            IsoCode = "MKD",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 129,
                            IsoCode = "NOR",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 130,
                            IsoCode = "OMN",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 131,
                            IsoCode = "PAK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 132,
                            IsoCode = "PLW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 133,
                            IsoCode = "PAN",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 134,
                            IsoCode = "PNG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 135,
                            IsoCode = "PRY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 136,
                            IsoCode = "PER",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 137,
                            IsoCode = "PHL",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 138,
                            IsoCode = "POL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 139,
                            IsoCode = "PRT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 140,
                            IsoCode = "QAT",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 141,
                            IsoCode = "ROU",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 142,
                            IsoCode = "RUS",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 143,
                            IsoCode = "RWA",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 144,
                            IsoCode = "KNA",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 145,
                            IsoCode = "LCA",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 146,
                            IsoCode = "VCT",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 147,
                            IsoCode = "WSM",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 148,
                            IsoCode = "SMR",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 149,
                            IsoCode = "STP",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 150,
                            IsoCode = "SAU",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 151,
                            IsoCode = "SEN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 152,
                            IsoCode = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 153,
                            IsoCode = "SYC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 154,
                            IsoCode = "SLE",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 155,
                            IsoCode = "SGP",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 156,
                            IsoCode = "SVK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 157,
                            IsoCode = "SVN",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 158,
                            IsoCode = "SLB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 159,
                            IsoCode = "SOM",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 160,
                            IsoCode = "ZAF",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 161,
                            IsoCode = "SSD",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 162,
                            IsoCode = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 163,
                            IsoCode = "LKA",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 164,
                            IsoCode = "SDN",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 165,
                            IsoCode = "SUR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 166,
                            IsoCode = "SWE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 167,
                            IsoCode = "CHE",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 168,
                            IsoCode = "SYR",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 169,
                            IsoCode = "TWN",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 170,
                            IsoCode = "TJK",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 171,
                            IsoCode = "TZA",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 172,
                            IsoCode = "THA",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 173,
                            IsoCode = "TLS",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 174,
                            IsoCode = "TGO",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 175,
                            IsoCode = "TON",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 176,
                            IsoCode = "TTO",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 177,
                            IsoCode = "TUN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 178,
                            IsoCode = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 179,
                            IsoCode = "TKM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 180,
                            IsoCode = "TUV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 181,
                            IsoCode = "UGA",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 182,
                            IsoCode = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 183,
                            IsoCode = "ARE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 184,
                            IsoCode = "GBR",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 185,
                            IsoCode = "USA",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 186,
                            IsoCode = "URY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 187,
                            IsoCode = "UZB",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 188,
                            IsoCode = "VUT",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 189,
                            IsoCode = "VAT",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 190,
                            IsoCode = "VEN",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 191,
                            IsoCode = "VNM",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 192,
                            IsoCode = "YEM",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 193,
                            IsoCode = "ZMB",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 194,
                            IsoCode = "ZWE",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrador",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Profesor",
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Estudiante",
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Scheduled", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Scheduled");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProfileUser", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ListProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyFlow.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ListUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Course", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.User", "Teacher")
                        .WithMany("ListCourse")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Enrollment", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Course", "Course")
                        .WithMany("ListEnrollment")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyFlow.DAL.Entities.User", "Student")
                        .WithMany("ListEnrollment")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Notification", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("StudyFlow.DAL.Entities.User", "User")
                        .WithMany("ListNotification")
                        .HasForeignKey("UserId");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Scheduled", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Subject", "Subject")
                        .WithMany("ListScheduled")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Subject", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Course", "Course")
                        .WithMany("ListSubject")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.User", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Course", b =>
                {
                    b.Navigation("ListEnrollment");

                    b.Navigation("ListSubject");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Subject", b =>
                {
                    b.Navigation("ListScheduled");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.User", b =>
                {
                    b.Navigation("ListCourse");

                    b.Navigation("ListEnrollment");

                    b.Navigation("ListNotification");
                });
#pragma warning restore 612, 618
        }
    }
}
