// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyFlow.DAL.Data;

#nullable disable

namespace StudyFlow.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241004005410_ModifiedEntityAnnounceToUseDates")]
    partial class ModifiedEntityAnnounceToUseDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("82153fbf-6d95-4560-9d7a-cf5696c04eb8"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("7d99b209-031e-4279-ad88-be7428db3ad3"),
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = new Guid("136b260b-ef66-442d-b27a-96cf37bbfa2e"),
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            RoleId = new Guid("7d99b209-031e-4279-ad88-be7428db3ad3")
                        },
                        new
                        {
                            UserId = new Guid("09c5da1f-3f23-4ddd-bb23-4629ff1d77a3"),
                            RoleId = new Guid("136b260b-ef66-442d-b27a-96cf37bbfa2e")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Announce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternateLinks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleDriveLinks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("YouTubeVideos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Announces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e38fe8f1-a6b4-4cbf-aafa-fb0c9ff9169f"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "Vamos a discutir los conceptos básicos de construcción de software y su importancia en el desarrollo de sistemas robustos.",
                            IsDeleted = false,
                            Title = "Introducción a la Construcción de Software",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("c5f68b30-29b7-4bf9-bb74-84676049d76a"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "En esta sesión aprenderemos sobre la importancia de las pruebas unitarias y cómo aplicarlas efectivamente.",
                            IsDeleted = false,
                            Title = "Pruebas Unitarias en Construcción de Software",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("37109139-b083-49d9-8827-db0015acbcc9"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "Exploraremos cómo la refactorización puede mejorar el código sin modificar su funcionalidad y las buenas prácticas para mantenerlo limpio.",
                            IsDeleted = false,
                            Title = "Refactorización y Buenas Prácticas",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("fad2ef4a-b4e0-4636-be44-b63a085cd644"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "Hablaremos sobre cómo implementar integración continua para detectar problemas antes de que lleguen a producción.",
                            IsDeleted = false,
                            Title = "Integración Continua (CI) en Proyectos de Software",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("9df4ac53-8965-451c-a7ec-c4a7804f39d8"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "Aprenderemos cómo configurar un entorno de desarrollo local y la importancia de prácticas DevOps en el ciclo de desarrollo.",
                            IsDeleted = false,
                            Title = "Entorno de Desarrollo Local y DevOps",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("777c8691-03b0-407f-9b80-5f857096a2a9"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "Analizaremos cómo gestionar dependencias del proyecto y las mejores prácticas para el control de versiones con Git.",
                            IsDeleted = false,
                            Title = "Gestión de Dependencias y Control de Versiones",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("48ef382f-1e19-4cd3-9a71-12162bd854a1"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "Exploraremos cómo aplicar metodologías ágiles, como Scrum y Kanban, durante el desarrollo de software.",
                            IsDeleted = false,
                            Title = "Metodologías Ágiles en la Construcción de Software",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("a59a2ac1-719a-45b6-bf88-7b555b2bf3c1"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "La documentación es esencial para la construcción de software de calidad. Discutiremos cómo documentar adecuadamente el proyecto.",
                            IsDeleted = false,
                            Title = "Documentación del Código y del Proyecto",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("73f4d0ca-7b92-432a-9a98-c34c2cd08051"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "Aprenderemos sobre los patrones de diseño y cómo aplicarlos para construir una arquitectura robusta.",
                            IsDeleted = false,
                            Title = "Arquitectura y Patrones de Diseño",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        },
                        new
                        {
                            Id = new Guid("7bc449cc-b16e-4682-9b49-4ed86260a1d2"),
                            AlternateLinks = "[]",
                            CourseId = new Guid("e70b6d49-1025-4cdb-b25d-f9c5dbe8d8ec"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleDriveLinks = "[]",
                            HtmlContent = "Veremos herramientas como Visual Studio, Docker y Jenkins, que facilitan el proceso de construcción de software.",
                            IsDeleted = false,
                            Title = "Herramientas para la Construcción de Software",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6fe44fdc-cac4-4d08-82d6-8a672b6960c0"),
                            YouTubeVideos = "[]"
                        });
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsoCode = "AFG",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            IsoCode = "ALB",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            IsoCode = "DZA",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            IsoCode = "AND",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            IsoCode = "AGO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            IsoCode = "ATG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            IsoCode = "ARG",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            IsoCode = "ARM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            IsoCode = "AUS",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            IsoCode = "AUT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            IsoCode = "AZE",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            IsoCode = "BHS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            IsoCode = "BHR",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            IsoCode = "BGD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            IsoCode = "BRB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            IsoCode = "BLR",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            IsoCode = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            IsoCode = "BLZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            IsoCode = "BEN",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            IsoCode = "BTN",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            IsoCode = "BOL",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            IsoCode = "BIH",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            IsoCode = "BWA",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            IsoCode = "BRA",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            IsoCode = "BRN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            IsoCode = "BGR",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            IsoCode = "BFA",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            IsoCode = "BDI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            IsoCode = "CPV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            IsoCode = "KHM",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            IsoCode = "CMR",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            IsoCode = "CAN",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            IsoCode = "CAF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            IsoCode = "TCD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            IsoCode = "CHL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            IsoCode = "CHN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            IsoCode = "COL",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            IsoCode = "COM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            IsoCode = "COG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 40,
                            IsoCode = "COD",
                            Name = "Congo, Democratic Republic of the"
                        },
                        new
                        {
                            Id = 41,
                            IsoCode = "CRI",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            IsoCode = "HRV",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            IsoCode = "CUB",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            IsoCode = "CYP",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            IsoCode = "CZE",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 46,
                            IsoCode = "DNK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 47,
                            IsoCode = "DJI",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48,
                            IsoCode = "DMA",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            IsoCode = "DOM",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50,
                            IsoCode = "ECU",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 51,
                            IsoCode = "EGY",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 52,
                            IsoCode = "SLV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 53,
                            IsoCode = "GNQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 54,
                            IsoCode = "ERI",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 55,
                            IsoCode = "EST",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 56,
                            IsoCode = "SWZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 57,
                            IsoCode = "ETH",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 58,
                            IsoCode = "FJI",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 59,
                            IsoCode = "FIN",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 60,
                            IsoCode = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = 61,
                            IsoCode = "GAB",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 62,
                            IsoCode = "GMB",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 63,
                            IsoCode = "GEO",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 64,
                            IsoCode = "DEU",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 65,
                            IsoCode = "GHA",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 66,
                            IsoCode = "GRC",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 67,
                            IsoCode = "GRD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 68,
                            IsoCode = "GTM",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 69,
                            IsoCode = "GIN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 70,
                            IsoCode = "GNB",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 71,
                            IsoCode = "GUY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 72,
                            IsoCode = "HTI",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 73,
                            IsoCode = "HND",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 74,
                            IsoCode = "HUN",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 75,
                            IsoCode = "ISL",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 76,
                            IsoCode = "IND",
                            Name = "India"
                        },
                        new
                        {
                            Id = 77,
                            IsoCode = "IDN",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 78,
                            IsoCode = "IRN",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 79,
                            IsoCode = "IRQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 80,
                            IsoCode = "IRL",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 81,
                            IsoCode = "ISR",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 82,
                            IsoCode = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 83,
                            IsoCode = "JAM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 84,
                            IsoCode = "JPN",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 85,
                            IsoCode = "JOR",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 86,
                            IsoCode = "KAZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 87,
                            IsoCode = "KEN",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 88,
                            IsoCode = "KIR",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 89,
                            IsoCode = "PRK",
                            Name = "Korea, North"
                        },
                        new
                        {
                            Id = 90,
                            IsoCode = "KOR",
                            Name = "Korea, South"
                        },
                        new
                        {
                            Id = 91,
                            IsoCode = "KWT",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            IsoCode = "KGZ",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            IsoCode = "LAO",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            IsoCode = "LVA",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            IsoCode = "LBN",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            IsoCode = "LSO",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            IsoCode = "LBR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            IsoCode = "LBY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            IsoCode = "LIE",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            IsoCode = "LTU",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            IsoCode = "LUX",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            IsoCode = "MDG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            IsoCode = "MWI",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            IsoCode = "MYS",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            IsoCode = "MDV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            IsoCode = "MLI",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            IsoCode = "MLT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            IsoCode = "MHL",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            IsoCode = "MRT",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            IsoCode = "MUS",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            IsoCode = "MEX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            IsoCode = "FSM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            IsoCode = "MDA",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            IsoCode = "MCO",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            IsoCode = "MNG",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            IsoCode = "MNE",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            IsoCode = "MAR",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            IsoCode = "MOZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            IsoCode = "MMR",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 120,
                            IsoCode = "NAM",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            IsoCode = "NRU",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            IsoCode = "NPL",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            IsoCode = "NLD",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            IsoCode = "NZL",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            IsoCode = "NIC",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            IsoCode = "NER",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            IsoCode = "NGA",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            IsoCode = "MKD",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 129,
                            IsoCode = "NOR",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 130,
                            IsoCode = "OMN",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 131,
                            IsoCode = "PAK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 132,
                            IsoCode = "PLW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 133,
                            IsoCode = "PAN",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 134,
                            IsoCode = "PNG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 135,
                            IsoCode = "PRY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 136,
                            IsoCode = "PER",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 137,
                            IsoCode = "PHL",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 138,
                            IsoCode = "POL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 139,
                            IsoCode = "PRT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 140,
                            IsoCode = "QAT",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 141,
                            IsoCode = "ROU",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 142,
                            IsoCode = "RUS",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 143,
                            IsoCode = "RWA",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 144,
                            IsoCode = "KNA",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 145,
                            IsoCode = "LCA",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 146,
                            IsoCode = "VCT",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 147,
                            IsoCode = "WSM",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 148,
                            IsoCode = "SMR",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 149,
                            IsoCode = "STP",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 150,
                            IsoCode = "SAU",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 151,
                            IsoCode = "SEN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 152,
                            IsoCode = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 153,
                            IsoCode = "SYC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 154,
                            IsoCode = "SLE",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 155,
                            IsoCode = "SGP",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 156,
                            IsoCode = "SVK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 157,
                            IsoCode = "SVN",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 158,
                            IsoCode = "SLB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 159,
                            IsoCode = "SOM",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 160,
                            IsoCode = "ZAF",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 161,
                            IsoCode = "SSD",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 162,
                            IsoCode = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 163,
                            IsoCode = "LKA",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 164,
                            IsoCode = "SDN",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 165,
                            IsoCode = "SUR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 166,
                            IsoCode = "SWE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 167,
                            IsoCode = "CHE",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 168,
                            IsoCode = "SYR",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 169,
                            IsoCode = "TWN",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 170,
                            IsoCode = "TJK",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 171,
                            IsoCode = "TZA",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 172,
                            IsoCode = "THA",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 173,
                            IsoCode = "TLS",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 174,
                            IsoCode = "TGO",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 175,
                            IsoCode = "TON",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 176,
                            IsoCode = "TTO",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 177,
                            IsoCode = "TUN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 178,
                            IsoCode = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 179,
                            IsoCode = "TKM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 180,
                            IsoCode = "TUV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 181,
                            IsoCode = "UGA",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 182,
                            IsoCode = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 183,
                            IsoCode = "ARE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 184,
                            IsoCode = "GBR",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 185,
                            IsoCode = "USA",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 186,
                            IsoCode = "URY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 187,
                            IsoCode = "UZB",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 188,
                            IsoCode = "VUT",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 189,
                            IsoCode = "VAT",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 190,
                            IsoCode = "VEN",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 191,
                            IsoCode = "VNM",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 192,
                            IsoCode = "YEM",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 193,
                            IsoCode = "ZMB",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 194,
                            IsoCode = "ZWE",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HaveLogo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2c79f89-1f3e-4128-9074-4b3275391ec6"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4376),
                            Description = "Mathematics is the study of numbers, quantities, and shapes.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Mathematics",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4390)
                        },
                        new
                        {
                            Id = new Guid("25c9d163-4eae-462d-9aea-a0c24c13fba4"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4393),
                            Description = "Science is the study of the natural world.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Science",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4394)
                        },
                        new
                        {
                            Id = new Guid("fe3e09a3-e7ff-48b9-8271-39a542d43058"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4397),
                            Description = "Computer science is the study of algorithmic processes, computational machines, and computation itself.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Computer Science",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4397)
                        },
                        new
                        {
                            Id = new Guid("3560514b-f59b-45a5-bf9c-547c26f0459e"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4400),
                            Description = "History is the study of the past.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "History",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4401)
                        },
                        new
                        {
                            Id = new Guid("64bbd412-6af9-4a0e-b233-0d214ba2170a"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4404),
                            Description = "Geography is the study of places and the relationships between people and their environments.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Geography",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4404)
                        },
                        new
                        {
                            Id = new Guid("a77fdf74-fe95-4a4e-a887-6c86cafbfc8e"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4406),
                            Description = "English is the study of the English language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "English",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4407)
                        },
                        new
                        {
                            Id = new Guid("60a86760-8d19-4390-96ce-98289cad84ec"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4412),
                            Description = "Spanish is the study of the Spanish language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Spanish",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4413)
                        },
                        new
                        {
                            Id = new Guid("a9fb12e7-f141-48ec-8eb9-1ec909316112"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4415),
                            Description = "French is the study of the French language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "French",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4416)
                        },
                        new
                        {
                            Id = new Guid("4bef2ae1-75c6-46ca-8083-15a7cc861001"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4418),
                            Description = "German is the study of the German language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "German",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4418)
                        },
                        new
                        {
                            Id = new Guid("5e4cfebf-9356-40b3-bd84-272792fa2ba2"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4422),
                            Description = "Italian is the study of the Italian language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Italian",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4422)
                        },
                        new
                        {
                            Id = new Guid("36753970-2553-4cdb-b6dd-751056a2e9cf"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4425),
                            Description = "Chinese is the study of the Chinese language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Chinese",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4425)
                        },
                        new
                        {
                            Id = new Guid("5c816d8a-89bf-4346-9a53-d5e95f0bc1ee"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4428),
                            Description = "Japanese is the study of the Japanese language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Japanese",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4428)
                        },
                        new
                        {
                            Id = new Guid("1cd7f3aa-1573-4b22-8f02-004d9f029f49"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4431),
                            Description = "Korean is the study of the Korean language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Korean",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4431)
                        },
                        new
                        {
                            Id = new Guid("34adbfc7-b758-44b1-9866-8697cb677ef4"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4434),
                            Description = "Arabic is the study of the Arabic language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Arabic",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4434)
                        },
                        new
                        {
                            Id = new Guid("ac01df60-7abb-48f0-8511-e52e1c0d7016"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4438),
                            Description = "Russian is the study of the Russian language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Russian",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4439)
                        },
                        new
                        {
                            Id = new Guid("20e78286-8f77-42b7-9cff-47c36c94490f"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4442),
                            Description = "Portuguese is the study of the Portuguese language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Portuguese",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4442)
                        },
                        new
                        {
                            Id = new Guid("08d4c5b1-51ab-41ff-b7ea-85820ae54a3b"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4445),
                            Description = "Dutch is the study of the Dutch language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Dutch",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4445)
                        },
                        new
                        {
                            Id = new Guid("8c5d4303-2c9b-4214-b85d-a8f930b9c8b3"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4448),
                            Description = "Swedish is the study of the Swedish language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Swedish",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4449)
                        },
                        new
                        {
                            Id = new Guid("711e494b-b293-4e80-9027-04af36e13fd9"),
                            CreatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4451),
                            Description = "Norwegian is the study of the Norwegian language.",
                            HaveLogo = false,
                            IsEnabled = false,
                            Name = "Norwegian",
                            TeacherId = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            UpdatedAt = new DateTime(2024, 10, 3, 19, 54, 10, 224, DateTimeKind.Local).AddTicks(4451)
                        });
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Scheduled", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("SubjectId", "ScheduledDate");

                    b.ToTable("Scheduleds");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HaveProfilePicture")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d260dbd-fe2f-4a9b-b1af-bf062fb52359"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "25d9722d-1066-433c-a8e8-21b8d9c7ee14",
                            CountryId = 43,
                            Email = "teacheruser@example.com",
                            EmailConfirmed = true,
                            FirstName = "Teacher",
                            HaveProfilePicture = false,
                            IsEnabled = false,
                            IsOnline = false,
                            LastName = "User",
                            LockoutEnabled = true,
                            NormalizedEmail = "TEACHERUSER@EXAMPLE.COM",
                            NormalizedUserName = "TEACHERUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEDmLNBjtiPz6TDWPndWQyPd1F08FpZWBv7UkZRBbRardiGHi4HiVrS6Ons6sfo20kQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "63bbef28-2830-4faf-93ea-2b07b76ee02f",
                            TwoFactorEnabled = false,
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("09c5da1f-3f23-4ddd-bb23-4629ff1d77a3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ef81135-a9e2-4af7-ac30-7f0b28991762",
                            CountryId = 35,
                            Email = "studentuser@example.com",
                            EmailConfirmed = true,
                            FirstName = "Student",
                            HaveProfilePicture = false,
                            IsEnabled = false,
                            IsOnline = false,
                            LastName = "User",
                            LockoutEnabled = true,
                            NormalizedEmail = "STUDENTUSER@EXAMPLE.COM",
                            NormalizedUserName = "STUDENTUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJLLJg3M9/06eQc6a78/jA9AAtuxFr1znDNhnWM/WYAntaB4bENnSoC0JmPLmMVYMg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "341f2653-32e2-414c-8633-d178c3839ca9",
                            TwoFactorEnabled = false,
                            UserType = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyFlow.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Announce", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Course", "Course")
                        .WithMany("Announces")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyFlow.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Course", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.User", "Teacher")
                        .WithMany("ListCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Enrollment", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Course", "Course")
                        .WithMany("ListEnrollment")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyFlow.DAL.Entities.User", "Student")
                        .WithMany("ListEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Notification", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyFlow.DAL.Entities.User", "User")
                        .WithMany("ListNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Scheduled", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Subject", "Subject")
                        .WithMany("ListScheduled")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Subject", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Course", "Course")
                        .WithMany("ListSubject")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.User", b =>
                {
                    b.HasOne("StudyFlow.DAL.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Course", b =>
                {
                    b.Navigation("Announces");

                    b.Navigation("ListEnrollment");

                    b.Navigation("ListSubject");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.Subject", b =>
                {
                    b.Navigation("ListScheduled");
                });

            modelBuilder.Entity("StudyFlow.DAL.Entities.User", b =>
                {
                    b.Navigation("ListCourses");

                    b.Navigation("ListEnrollments");

                    b.Navigation("ListNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
